### ISSUE TITLE
pyinstaller: error: argument --add-data: invalid add_data_or_binary value: 'jadx:jadx'

### ISSUE THREAD

**Issue by gopinath6** [vincentcox/StaCoAn#12]
Any idea what am missing?
Using Windows 7
C:\Users\XXXXXX\StaCoAn-master\StaCoAn-master>pyinstaller main.py --onefile --add-data jadx:jadx -p jadx --icon icon.ico --name stacoan --clean
usage: pyinstaller [-h] [-v] [-D] [-F] [--specpath DIR] [-n NAME]
                   [--add-data <SRC;DEST or SRC:DEST>]
                   [--add-binary <SRC;DEST or SRC:DEST>] [-p DIR]
                   [--hidden-import MODULENAME]
                   [--additional-hooks-dir HOOKSPATH]
                   [--runtime-hook RUNTIME_HOOKS] [--exclude-module EXCLUDES]
                   [--key KEY] [-d] [-s] [--noupx] [-c] [-w]
                   [-i <FILE.ico or FILE.exe,ID or FILE.icns>]
                   [--version-file FILE] [-m <FILE or XML>] [-r RESOURCE]
                   [--uac-admin] [--uac-uiaccess] [--win-private-assemblies]
                   [--win-no-prefer-redirects]
                   [--osx-bundle-identifier BUNDLE_IDENTIFIER]
                   [--runtime-tmpdir PATH] [--distpath DIR]
                   [--workpath WORKPATH] [-y] [--upx-dir UPX_DIR] [-a]
                   [--clean] [--log-level LEVEL]
                   scriptname [scriptname ...]
pyinstaller: error: argument --add-data: invalid add_data_or_binary value: 'jadx:jadx'

**Comment by vincentcox** [comment]
It was not a problem on your end, but a change in the building process I forget to update in the README file. 

https://github.com/vincentcox/StaCoAn/commit/4b1d02b4bf57a8f40068d6edbc970d456fc698c3 fixes this. 

In your case it would be `C:\Users\XXXXXX\StaCoAn-master\StaCoAn-master>pyinstaller main.py --onefile --icon icon.ico --name stacoan --clean`
