### ISSUE TITLE
Python : can't open file

### ISSUE THREAD

**Issue by Sigri44** [vincentcox/StaCoAn#25]
`python: can't open file '/StaCoAn/src/main.py': [Errno 2] No such file or directory`

![image](https://user-images.githubusercontent.com/9304947/36097348-e3d72d28-0ffa-11e8-862b-3187549103af.png)

**Comment by vincentcox** [comment]
https://github.com/vincentcox/StaCoAn/commit/b07240a050667315e5db4a9d2326bd40de86860e

Thanks for notifying me! :)
