### ISSUE TITLE
No module named 'yattag'

### ISSUE THREAD

**Issue by GuillotJessica** [vincentcox/StaCoAn#28]
hello,
trying to use StaCoAn on windows using bash I'm having the following error
No module named 'yattag',
any clue? thx

**Comment by Ayowel** [comment]
Hi,

Did you properly run `pip3 install -r src/requirements.txt` ? The `yattag` module should be installed by running it.
Also, ensure that you're running the app with python3 (if you don't have python3, run `python --version` to check), otherwise the module installation will be of no use.

**Comment by vincentcox** [comment]
Hi there,

Thanks for taking time to report this. 

Are you sure that you followed all the steps?

`git clone https://github.com/vincentcox/StaCoAn/`

`cd StaCoAn/src`

Make sure that you have pip3 installed:

`sudo apt-get install python3-pip`

Install the required python packages:

`pip3 install -r requirements.txt`

Run StaCoAn:

`python3 stacoan.py yourApp.apk`

You can also use a binary from the releases: https://github.com/vincentcox/StaCoAn/releases

If it's still an issue, feel free to re-open this.

**Comment by GuillotJessica** [comment]
on windows, there is no such at-get install even on bash I hink so I did try to do it my way

**Comment by vincentcox** [comment]
What happens when you use the command `pip3 install -r requirements.txt`?

**Comment by kubaunold** [comment]
For me it was the fact, that `yattag` didn't work with Python 3.7 (only up to 3.5). So I removed the module
`pip uninstall yattag`
Then installed it once again, this time making sure I use `pip`, not `pip3` command
`pip install yattag`
Now I was able to run my file w/out any problems by: (of course after switching my compiler to Python 2.7)
`python .\main.py`
