### ISSUE TITLE
Wrong APK like a directory

### ISSUE THREAD

**Issue by b4b857f6ee** [vincentcox/StaCoAn#29]
Hi,

When i run the docker command i get this : 

[ERROR] ERROR: Unknown error: [Errno 21] Is a directory: 'myapp.apk'.

didn't understand why... did anyone get this too?

**Comment by Ayowel** [comment]
Hi,

It looks like you created a folder named "myapp.apk" while it should be called "myapp". myapp.apk is expected to be a file.

Don't know what I'm talking about ? Run ```ls -l `find . -name myapp.apk` ``` in your directory, if you created a file/directory with that name, it should appear. If the first letter in the line is a 'd', you created a directory.

**Comment by vincentcox** [comment]
@Ayowel, thanks for the reply!
@b4b857f6ee, let me know what the result of the above answer is.

**Comment by b4b857f6ee** [comment]
Hi, 

My command is : 
docker run -e JAVA_OPTS="-Xms2048m -Xmx2048m" -p 8000:8000 -v /var/lib/docker/volumes/c7eabfc015ae3f7df9ce26b43d2c325bbdc61411b18c176a5c7ac3133f882a22/_data:/myapk -i -t stacoan myapk.apk

i get : [ERROR] ERROR: Unknown error: [Errno 21] Is a directory: 'myapk.apk'.

I already check the file with ls -lsha and i get this : 
4.0K drwxr-xr-x 11 root root 4.0K Feb 14 15:27 myapk
5.2M -rw-r--r--  1 root root 5.2M Feb 14 15:26 myapk.apk

nb : In my point of view, i didn't know docker so maybe you can add some explain or link to explain how to map volume with docker :)

**Comment by vincentcox** [comment]
Thanks for letting me know and taking time to test this again. I will try to reproduce the issue as soon as I am home. 

In a week I will make a drag and drop web interface for stocoan, so these kind of issues will be eliminated. 

I really want to make this program as accessible as possible. Will keep you updated!

**Comment by b4b857f6ee** [comment]
"drag and drop web interface for stocoan" That's going to be so user friendly :D. And that's how you get the most audience. :)

Good luck!

**Comment by vincentcox** [comment]
Update: we are working on the develop branch, so we didn't forget about this issue :) It's not yet done, but I expect to get a merge to master and a new release within the week.

**Comment by b4b857f6ee** [comment]
Nice thank you!

**Comment by vincentcox** [comment]
Implemented in last commit (Master) and builds. Feel free to re-open this if you keep getting the same issue with the latest build/master code.
