### ISSUE TITLE
Request: Rebranding

### ISSUE THREAD

**Issue by Kevin-De-Koninck** [vincentcox/StaCoAn#3]
StaCoAn is a hard name to remember and pronounce. It could help to rebrand it to something else, for example 'Stacy'.

**Comment by vincentcox** [comment]
I will keep this issue open so others can vote for a namechange. 
![image](https://user-images.githubusercontent.com/9286611/36033956-b7f08884-0db2-11e8-8ab0-42b8f117d66c.png)
![image](https://user-images.githubusercontent.com/9286611/36033979-c09ff38e-0db2-11e8-87f4-5b687ecceff6.png)

**Comment by Ayowel** [comment]
Hi,

Saw the question a few days ago but I didn't answer at the time.
`StaCoAn` can indeed prove hard to remember and/or share, however I feel like the name should still be meaningful, which `Stacy` is not as far as I can see.
`SCA` could be a straight-forward acronym but is already used for several projects, so it might not be the best idea.
`StaCA` could be a bit easier to use, as it doesn't require much work to pronounce, isn't widely spread and should be pronounceable in most language with little to no modifications (the 'St' might be a bit hard to say for some, but that's about it).

Or you could decide to have a bit of fun with something like `SCeAl` (Static CodE AnaLyser), pronounce 'skill', say 'ea' as in 'tea', write almost as 'seal'. Guaranteed confusion (or you could just say it's pronounced as 'seal' and has one 'c', less fun and different pronunciation).
On a more serious note, you could very well use a name with no relation whatsoever with 'Static Code Analyser', but I think that you'd better avoid using something that could look like an acronym while it isn't.

I'd personally go for **StaCA** (short, meaningful, easy to say & to remember, only 6 repositories when searching that name in github and none with that exact name so no risk of confusion, ...).

**Comment by vincentcox** [comment]
Thanks everybody for your input. I have to agree that "StaCoAn" is indeed hard to remember and pronounce. But I think the tool came at a stage it is hard to do a namechange. Several blogs and articles have appeared and I think it's just to late to change the name.

**Comment by Kevin-De-Koninck** [comment]
Fyi, If you rename a repository on github (setting -> rename), the old URL (https://github.com/vincentcox/StaCoAn) will still exist and redirect you to the new page (e.g. https://github.com/vincentcox/Stacy) so I don't think that it's too late. 

StaCoAn can still be the main title but you could add an a.k.a. 'new_name'.
