### ISSUE TITLE
New exclusion

### ISSUE THREAD

**Issue by 4val0v** [vincentcox/StaCoAn#35]
Please add
http://schemas.amazon.com/apk/res/android
http://schemas.androd.com/apk/res/android

**Comment by vincentcox** [comment]
Can you give an example where it should be excluded? 
Or do you mean: Exclude this for all found URL's?

**Comment by 4val0v** [comment]
Exclude this for all found URL

**Comment by vincentcox** [comment]
Done! 😄  (develop branch) https://github.com/vincentcox/StaCoAn/commit/72278310480efc642a8debd346e541e7692ca066
Thanks for your input on this project!
