### ISSUE TITLE
Run script outside directory + apk outside directory

### ISSUE THREAD

**Issue by vincentcox** [vincentcox/StaCoAn#36]
When using an apk from a different directory 
![image](https://user-images.githubusercontent.com/9286611/36783240-b7d015fe-1c7b-11e8-9b60-87f40553cb0e.png)

**Comment by Ayowel** [comment]
Could you share the apk you're trying to decompile ? I can't seem to reproduce the bug with the `test-apk.apk` in Kali

**Comment by vincentcox** [comment]
A colleague sent it to me, but I also can't verify this. However, if I call the itself script from somewhere else, a lot of errors come up. 
I will add that to the roadmap to make a fix for this.
Thanks for testing this tough! 👍
