### ISSUE TITLE
Create a GitHub wiki

### ISSUE THREAD

**Issue by Kevin-De-Koninck** [vincentcox/StaCoAn#55]
You can create a GitHub wiki to describe how to use the tool on the different platforms. This will shorten your repo's README file, which improves it imho (readability, length, ease of access, ...)

**Comment by vincentcox** [comment]
Can you check if the wiki is editable for you?

**Comment by Kevin-De-Koninck** [comment]
I cannot edit it.

**Comment by vincentcox** [comment]
If I find the time to create a wiki I will certainly do it! Thanks for the suggestion. I add this to the roadmap.
