### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by thistehneisen** [vincentcox/StaCoAn#66]
```
┌─[nils@parrot]─[~/Code/Python/StaCoAn/docker]
└──╼ $sudo docker run -e JAVA_OPTS="-Xms2048m -Xmx2048m" -p 8888:8888 -p 7777:7777 -i -t stacoan
usage: stacoan.py [-h] [-p PATH [PATH ...]] [--disable-browser]
                  [--disable-server]
                  [--log-all | --log-errors | --log-warnings]
stacoan.py: error: unrecognized arguments: --enable-server
```

**Comment by vincentcox** [comment]
Thanks for reporting this and creating an issue. I will try to make a fix for this when I am back from vacation.

**Comment by vincentcox** [comment]
I can confirm the issue:

![image](https://user-images.githubusercontent.com/9286611/41902154-0d359d52-7933-11e8-9a7b-8c630d4ac94a.png)

The commit "fix docker" is not working, need to investigate it further

**Comment by Kevin-De-Koninck** [comment]
I assume this is a carriage return issue. Did you edit the file using windows? if so, do `dos2unix stacoan.sh`. If that is the case, you could add it in the docker file or so.

**Comment by vincentcox** [comment]
Fixed in https://github.com/vincentcox/StaCoAn/commit/fe154705a5dc2ca1a8ba3fdd3d13772e8f228bfe (I've put dos2unix inside the docker container)

Follow these instructions to get it up and running again:
```
rm -rf StaCoAn
git clone https://github.com/vincentcox/StaCoAn
cd StaCoAn/docker
docker build --no-cache . -t stacoan # (--no-cache is needed!)
docker run -e JAVA_OPTS="-Xms2048m -Xmx2048m" -p 8888:8888 -p 7777:7777 -i -t stacoan

```
