### ISSUE TITLE
Command line option?

### ISSUE THREAD

**Issue by StephenQuirolgico** [vincentcox/StaCoAn#78]
Can this be run from a command line?

**Comment by vincentcox** [comment]
Yes this is possible:
```
python3 stacoan.py -p yourApp.apk
```

I am closing this issue, if you have questions, feel free to ask!

**Comment by StephenQuirolgico** [comment]
Vincent,

Thank you. When will IPA files be supported?

Steve

**Comment by vincentcox** [comment]
@StephenQuirolgico , for now it's technically impossible to decrypt iOS apps in a static way. There are tools to do it in runtime on a device, by dumping it from memory. But that requires a full device which is jailbroken and with the correct Cydia tools installed.  But this program takes a static approach so it will not be very likely to happen anytime soon.
