### ISSUE TITLE
Gibberish content in the generated report.

### ISSUE THREAD

**Issue by DeepSpaceHarbor** [vincentcox/StaCoAn#9]
**Summary:**
See the attached images. The app didn't show any errors. 
The generated report contains gibberish data. Tried to rebuild the report 3 times, ended with the same result.

**Details:**
.apk file: https://play.google.com/store/apps/details?id=com.mkdingo.goran.signlangugage
The file was downloaded via [APKPure](https://apkpure.com/region-free-apk-download?p=com.mkdingo.goran.signlangugage).
os: Linux mint 

**Proof of error:**
StaCoAn
![](https://i.imgur.com/uhlpNdA.png)

Jadx:
![](https://i.imgur.com/DmTEuyH.png)

**Additional info:**
The app uses Cyrillic characters for resources(ex: R.id.в, R.id.ж).
Could this be the cause of the problem?

**Comment by vincentcox** [comment]
Thanks for reporting! Currently there are some issues with Unicode in the program (as also pointed out in https://github.com/vincentcox/StaCoAn/issues/2). Will do some testing to find a solution.

**Comment by vincentcox** [comment]
Can you provide me one source file where the program crashes on? If this is not possible due NDA or other reasons it is ok. It just helps me with debugging.

**Comment by DeepSpaceHarbor** [comment]
I don't have the source code for this program. 
Only thing I have is the final apk file which was shared in the original post.

**Comment by vincentcox** [comment]
I managed to get a fix pushed. 

I tested your apk and it seems fine now:
![video 10-02-2018 22-38-11](https://user-images.githubusercontent.com/9286611/36066948-bef9e3f8-0eb3-11e8-94f8-52ace9377b81.gif)

Which generated the report:
![image](https://user-images.githubusercontent.com/9286611/36067407-fc28284e-0ebc-11e8-95d6-0808ce0003c1.png)


You can head over to the [release page](https://github.com/vincentcox/StaCoAn/releases) and grab the latest version.
